//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MachineFailureEntities : DbContext
    {
        public MachineFailureEntities()
            : base("name=MachineFailureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<FaultTypes> FaultTypes { get; set; }
        public virtual DbSet<Machines> Machines { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<Sites> Sites { get; set; }
    }
}
